name: Build
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
      - name: Build
        run: msbuild SteamRouteTool.sln -property:Configuration=Release
      - name: Zip release
        run: Compress-Archive ./SteamRouteTool/bin/Release/ release.zip
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: SteamRouteTool.zip
          path: ./release.zip
