name: Build
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2.0.0
      - name: Restore NuGet packages
        run: nuget restore SteamRouteTool.sln
      - name: Build
        run: msbuild SteamRouteTool.sln -property:Configuration=Release
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: SteamRouteTool
          path: ./SteamRouteTool/bin/Release
