name: Build
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2.0.0
      - name: Restore NuGet packages
        run: nuget restore SteamRouteTool.sln
      - name: Build
        run: msbuild SteamRouteTool.sln -m -property:Configuration=Release
      - name: Compress for release
        run: Compress-Archive .\SteamRouteTool\bin\Release SteamRouteTool.zip
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: SteamRouteTool.zip
          path: SteamRouteTool.zip
      - name: Delete old release
        uses: dev-drprasad/delete-tag-and-release@v1.0.1
        with:
          tag_name: release
      - name: Create Release
        uses: ncipollo/release-action@v1.14.0
        with:
          name: "SteamRouteTool"
          body: "Built with GitHub actions."
          artifacts: "*.zip"
          tag: release
