name: Build
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v2
      - name: Build
        run: msbuild SteamRouteTool.sln -property:Configuration=Release
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: SteamRouteTool.exe
          path: ./SteamRouteTool/bin/Release/*.exe
